spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8081

keycloak:
  auth-server-suffix-url: /realms/springbootkeycloak/protocol/openid-connect/token
  realm: springbootkeycloak
  auth-server-url: http://127.0.0.1:8000/auth
  ssl-required: external
  resource: login-app
  credentials:
    secret: puSfuLc9Lt8sf6RmAsqMhDpTPvS4BXvg
  use-resource-role-mappings: true
  bearer-only: true
